#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Music")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertArtistLoadRequest(ArtistLoadRequest instance);
    partial void UpdateArtistLoadRequest(ArtistLoadRequest instance);
    partial void DeleteArtistLoadRequest(ArtistLoadRequest instance);
    partial void InsertARTIST(ARTIST instance);
    partial void UpdateARTIST(ARTIST instance);
    partial void DeleteARTIST(ARTIST instance);
    partial void InsertSONG_RATED(SONG_RATED instance);
    partial void UpdateSONG_RATED(SONG_RATED instance);
    partial void DeleteSONG_RATED(SONG_RATED instance);
    partial void InsertSONG(SONG instance);
    partial void UpdateSONG(SONG instance);
    partial void DeleteSONG(SONG instance);
    #endregion
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ArtistLoadRequest> ArtistLoadRequests
		{
			get
			{
				return this.GetTable<ArtistLoadRequest>();
			}
		}
		
		public System.Data.Linq.Table<ARTIST> ARTISTs
		{
			get
			{
				return this.GetTable<ARTIST>();
			}
		}
		
		public System.Data.Linq.Table<SONG_RATED> SONG_RATEDs
		{
			get
			{
				return this.GetTable<SONG_RATED>();
			}
		}
		
		public System.Data.Linq.Table<SONG> SONGs
		{
			get
			{
				return this.GetTable<SONG>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectMusic")]
		public ISingleResult<SelectMusicResult> SelectMusic()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SelectMusicResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ArtistLoadRequest")]
	public partial class ArtistLoadRequest : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _ArtistId;
		
		private bool _Loaded;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnArtistIdChanging(int value);
    partial void OnArtistIdChanged();
    partial void OnLoadedChanging(bool value);
    partial void OnLoadedChanged();
    #endregion
		
		public ArtistLoadRequest()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArtistId", DbType="Int NOT NULL")]
		public int ArtistId
		{
			get
			{
				return this._ArtistId;
			}
			set
			{
				if ((this._ArtistId != value))
				{
					this.OnArtistIdChanging(value);
					this.SendPropertyChanging();
					this._ArtistId = value;
					this.SendPropertyChanged("ArtistId");
					this.OnArtistIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loaded", DbType="Bit NOT NULL")]
		public bool Loaded
		{
			get
			{
				return this._Loaded;
			}
			set
			{
				if ((this._Loaded != value))
				{
					this.OnLoadedChanging(value);
					this.SendPropertyChanging();
					this._Loaded = value;
					this.SendPropertyChanged("Loaded");
					this.OnLoadedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ARTIST")]
	public partial class ARTIST : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _NAME;
		
		private string _COMMENTS;
		
		private System.Nullable<int> _RATING;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnCOMMENTSChanging(string value);
    partial void OnCOMMENTSChanged();
    partial void OnRATINGChanging(System.Nullable<int> value);
    partial void OnRATINGChanged();
    #endregion
		
		public ARTIST()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMMENTS", DbType="VarChar(1024)")]
		public string COMMENTS
		{
			get
			{
				return this._COMMENTS;
			}
			set
			{
				if ((this._COMMENTS != value))
				{
					this.OnCOMMENTSChanging(value);
					this.SendPropertyChanging();
					this._COMMENTS = value;
					this.SendPropertyChanged("COMMENTS");
					this.OnCOMMENTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RATING", DbType="Int")]
		public System.Nullable<int> RATING
		{
			get
			{
				return this._RATING;
			}
			set
			{
				if ((this._RATING != value))
				{
					this.OnRATINGChanging(value);
					this.SendPropertyChanging();
					this._RATING = value;
					this.SendPropertyChanged("RATING");
					this.OnRATINGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SONG_RATED")]
	public partial class SONG_RATED : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _SONG_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSONG_IDChanging(int value);
    partial void OnSONG_IDChanged();
    #endregion
		
		public SONG_RATED()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SONG_ID", DbType="Int NOT NULL")]
		public int SONG_ID
		{
			get
			{
				return this._SONG_ID;
			}
			set
			{
				if ((this._SONG_ID != value))
				{
					this.OnSONG_IDChanging(value);
					this.SendPropertyChanging();
					this._SONG_ID = value;
					this.SendPropertyChanged("SONG_ID");
					this.OnSONG_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SONG")]
	public partial class SONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TITLE;
		
		private string _ARTIST;
		
		private string _ALBUM;
		
		private string _GENRE;
		
		private System.Nullable<long> _DURATION;
		
		private System.Nullable<long> _BITRATE;
		
		private System.Nullable<long> _FILESIZE;
		
		private int _RATING;
		
		private string _COMMENTS;
		
		private System.Nullable<int> _ARTIST_ID;
		
		private string _LOCATION;
		
		private int _ID;
		
		private bool _UPLOADED;
		
		private System.Data.Linq.Binary _HASH;
		
		private System.Nullable<System.DateTime> _UPDATED;
		
		private System.Nullable<System.DateTime> _CREATED;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTITLEChanging(string value);
    partial void OnTITLEChanged();
    partial void OnARTISTChanging(string value);
    partial void OnARTISTChanged();
    partial void OnALBUMChanging(string value);
    partial void OnALBUMChanged();
    partial void OnGENREChanging(string value);
    partial void OnGENREChanged();
    partial void OnDURATIONChanging(System.Nullable<long> value);
    partial void OnDURATIONChanged();
    partial void OnBITRATEChanging(System.Nullable<long> value);
    partial void OnBITRATEChanged();
    partial void OnFILESIZEChanging(System.Nullable<long> value);
    partial void OnFILESIZEChanged();
    partial void OnRATINGChanging(int value);
    partial void OnRATINGChanged();
    partial void OnCOMMENTSChanging(string value);
    partial void OnCOMMENTSChanged();
    partial void OnARTIST_IDChanging(System.Nullable<int> value);
    partial void OnARTIST_IDChanged();
    partial void OnLOCATIONChanging(string value);
    partial void OnLOCATIONChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUPLOADEDChanging(bool value);
    partial void OnUPLOADEDChanged();
    partial void OnHASHChanging(System.Data.Linq.Binary value);
    partial void OnHASHChanged();
    partial void OnUPDATEDChanging(System.Nullable<System.DateTime> value);
    partial void OnUPDATEDChanged();
    partial void OnCREATEDChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATEDChanged();
    #endregion
		
		public SONG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITLE", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string TITLE
		{
			get
			{
				return this._TITLE;
			}
			set
			{
				if ((this._TITLE != value))
				{
					this.OnTITLEChanging(value);
					this.SendPropertyChanging();
					this._TITLE = value;
					this.SendPropertyChanged("TITLE");
					this.OnTITLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARTIST", DbType="VarChar(256)")]
		public string ARTIST
		{
			get
			{
				return this._ARTIST;
			}
			set
			{
				if ((this._ARTIST != value))
				{
					this.OnARTISTChanging(value);
					this.SendPropertyChanging();
					this._ARTIST = value;
					this.SendPropertyChanged("ARTIST");
					this.OnARTISTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALBUM", DbType="VarChar(256)")]
		public string ALBUM
		{
			get
			{
				return this._ALBUM;
			}
			set
			{
				if ((this._ALBUM != value))
				{
					this.OnALBUMChanging(value);
					this.SendPropertyChanging();
					this._ALBUM = value;
					this.SendPropertyChanged("ALBUM");
					this.OnALBUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENRE", DbType="VarChar(256)")]
		public string GENRE
		{
			get
			{
				return this._GENRE;
			}
			set
			{
				if ((this._GENRE != value))
				{
					this.OnGENREChanging(value);
					this.SendPropertyChanging();
					this._GENRE = value;
					this.SendPropertyChanged("GENRE");
					this.OnGENREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DURATION", DbType="BigInt")]
		public System.Nullable<long> DURATION
		{
			get
			{
				return this._DURATION;
			}
			set
			{
				if ((this._DURATION != value))
				{
					this.OnDURATIONChanging(value);
					this.SendPropertyChanging();
					this._DURATION = value;
					this.SendPropertyChanged("DURATION");
					this.OnDURATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BITRATE", DbType="BigInt")]
		public System.Nullable<long> BITRATE
		{
			get
			{
				return this._BITRATE;
			}
			set
			{
				if ((this._BITRATE != value))
				{
					this.OnBITRATEChanging(value);
					this.SendPropertyChanging();
					this._BITRATE = value;
					this.SendPropertyChanged("BITRATE");
					this.OnBITRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FILESIZE", DbType="BigInt")]
		public System.Nullable<long> FILESIZE
		{
			get
			{
				return this._FILESIZE;
			}
			set
			{
				if ((this._FILESIZE != value))
				{
					this.OnFILESIZEChanging(value);
					this.SendPropertyChanging();
					this._FILESIZE = value;
					this.SendPropertyChanged("FILESIZE");
					this.OnFILESIZEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RATING", DbType="Int NOT NULL")]
		public int RATING
		{
			get
			{
				return this._RATING;
			}
			set
			{
				if ((this._RATING != value))
				{
					this.OnRATINGChanging(value);
					this.SendPropertyChanging();
					this._RATING = value;
					this.SendPropertyChanged("RATING");
					this.OnRATINGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMMENTS", DbType="VarChar(256)")]
		public string COMMENTS
		{
			get
			{
				return this._COMMENTS;
			}
			set
			{
				if ((this._COMMENTS != value))
				{
					this.OnCOMMENTSChanging(value);
					this.SendPropertyChanging();
					this._COMMENTS = value;
					this.SendPropertyChanged("COMMENTS");
					this.OnCOMMENTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARTIST_ID", DbType="Int")]
		public System.Nullable<int> ARTIST_ID
		{
			get
			{
				return this._ARTIST_ID;
			}
			set
			{
				if ((this._ARTIST_ID != value))
				{
					this.OnARTIST_IDChanging(value);
					this.SendPropertyChanging();
					this._ARTIST_ID = value;
					this.SendPropertyChanged("ARTIST_ID");
					this.OnARTIST_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATION", DbType="VarChar(1024)")]
		public string LOCATION
		{
			get
			{
				return this._LOCATION;
			}
			set
			{
				if ((this._LOCATION != value))
				{
					this.OnLOCATIONChanging(value);
					this.SendPropertyChanging();
					this._LOCATION = value;
					this.SendPropertyChanged("LOCATION");
					this.OnLOCATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPLOADED", DbType="Bit NOT NULL")]
		public bool UPLOADED
		{
			get
			{
				return this._UPLOADED;
			}
			set
			{
				if ((this._UPLOADED != value))
				{
					this.OnUPLOADEDChanging(value);
					this.SendPropertyChanging();
					this._UPLOADED = value;
					this.SendPropertyChanged("UPLOADED");
					this.OnUPLOADEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HASH", DbType="Binary(50)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary HASH
		{
			get
			{
				return this._HASH;
			}
			set
			{
				if ((this._HASH != value))
				{
					this.OnHASHChanging(value);
					this.SendPropertyChanging();
					this._HASH = value;
					this.SendPropertyChanged("HASH");
					this.OnHASHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED", DbType="Date")]
		public System.Nullable<System.DateTime> UPDATED
		{
			get
			{
				return this._UPDATED;
			}
			set
			{
				if ((this._UPDATED != value))
				{
					this.OnUPDATEDChanging(value);
					this.SendPropertyChanging();
					this._UPDATED = value;
					this.SendPropertyChanged("UPDATED");
					this.OnUPDATEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED", DbType="Date")]
		public System.Nullable<System.DateTime> CREATED
		{
			get
			{
				return this._CREATED;
			}
			set
			{
				if ((this._CREATED != value))
				{
					this.OnCREATEDChanging(value);
					this.SendPropertyChanging();
					this._CREATED = value;
					this.SendPropertyChanged("CREATED");
					this.OnCREATEDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class SelectMusicResult
	{
		
		private string _TITLE;
		
		private string _ARTIST;
		
		private string _GENRE;
		
		private int _SONG_RATING;
		
		private int _SONG_ID;
		
		private string _LOCATION;
		
		private System.Nullable<int> _ARTIST_RATING;
		
		public SelectMusicResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITLE", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string TITLE
		{
			get
			{
				return this._TITLE;
			}
			set
			{
				if ((this._TITLE != value))
				{
					this._TITLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARTIST", DbType="VarChar(256)")]
		public string ARTIST
		{
			get
			{
				return this._ARTIST;
			}
			set
			{
				if ((this._ARTIST != value))
				{
					this._ARTIST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENRE", DbType="VarChar(256)")]
		public string GENRE
		{
			get
			{
				return this._GENRE;
			}
			set
			{
				if ((this._GENRE != value))
				{
					this._GENRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SONG_RATING", DbType="Int NOT NULL")]
		public int SONG_RATING
		{
			get
			{
				return this._SONG_RATING;
			}
			set
			{
				if ((this._SONG_RATING != value))
				{
					this._SONG_RATING = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SONG_ID", DbType="Int NOT NULL")]
		public int SONG_ID
		{
			get
			{
				return this._SONG_ID;
			}
			set
			{
				if ((this._SONG_ID != value))
				{
					this._SONG_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATION", DbType="VarChar(1024)")]
		public string LOCATION
		{
			get
			{
				return this._LOCATION;
			}
			set
			{
				if ((this._LOCATION != value))
				{
					this._LOCATION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARTIST_RATING", DbType="Int")]
		public System.Nullable<int> ARTIST_RATING
		{
			get
			{
				return this._ARTIST_RATING;
			}
			set
			{
				if ((this._ARTIST_RATING != value))
				{
					this._ARTIST_RATING = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
