//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music
{
    using System;
    using System.Collections.Generic;
    
    public partial class MellowSong
    {
        public string TITLE { get; set; }
        public string ARTIST { get; set; }
        public string ALBUM { get; set; }
        public string GENRE { get; set; }
        public Nullable<long> DURATION { get; set; }
        public Nullable<long> BITRATE { get; set; }
        public Nullable<long> FILESIZE { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<int> ARTIST_ID { get; set; }
        public int ID { get; set; }
        public bool UPLOADED { get; set; }
        public string LOCATION { get; set; }
        public byte[] HASH { get; set; }
        public Nullable<System.DateTime> UPDATED { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<int> RATING { get; set; }
    }
}
