//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MusicModel", "FK_SONG_RATED_SONG", "SONG", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SqlAzureData.SONG), "SONG_RATED", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SqlAzureData.SONG_RATED), true)]

#endregion

namespace SqlAzureData
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MusicEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MusicEntities object using the connection string found in the 'MusicEntities' section of the application configuration file.
        /// </summary>
        public MusicEntities() : base("name=MusicEntities", "MusicEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MusicEntities object.
        /// </summary>
        public MusicEntities(string connectionString) : base(connectionString, "MusicEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MusicEntities object.
        /// </summary>
        public MusicEntities(EntityConnection connection) : base(connection, "MusicEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ARTIST> ARTIST
        {
            get
            {
                if ((_ARTIST == null))
                {
                    _ARTIST = base.CreateObjectSet<ARTIST>("ARTIST");
                }
                return _ARTIST;
            }
        }
        private ObjectSet<ARTIST> _ARTIST;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SONG> SONG
        {
            get
            {
                if ((_SONG == null))
                {
                    _SONG = base.CreateObjectSet<SONG>("SONG");
                }
                return _SONG;
            }
        }
        private ObjectSet<SONG> _SONG;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SONG_RATED> SONG_RATED
        {
            get
            {
                if ((_SONG_RATED == null))
                {
                    _SONG_RATED = base.CreateObjectSet<SONG_RATED>("SONG_RATED");
                }
                return _SONG_RATED;
            }
        }
        private ObjectSet<SONG_RATED> _SONG_RATED;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ARTIST EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToARTIST(ARTIST aRTIST)
        {
            base.AddObject("ARTIST", aRTIST);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SONG EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSONG(SONG sONG)
        {
            base.AddObject("SONG", sONG);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SONG_RATED EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSONG_RATED(SONG_RATED sONG_RATED)
        {
            base.AddObject("SONG_RATED", sONG_RATED);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MusicModel", Name="ARTIST")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ARTIST : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ARTIST object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="nAME">Initial value of the NAME property.</param>
        public static ARTIST CreateARTIST(global::System.Int32 id, global::System.String nAME)
        {
            ARTIST aRTIST = new ARTIST();
            aRTIST.ID = id;
            aRTIST.NAME = nAME;
            return aRTIST;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, false, "NAME");
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COMMENTS
        {
            get
            {
                return _COMMENTS;
            }
            set
            {
                OnCOMMENTSChanging(value);
                ReportPropertyChanging("COMMENTS");
                _COMMENTS = StructuralObject.SetValidValue(value, true, "COMMENTS");
                ReportPropertyChanged("COMMENTS");
                OnCOMMENTSChanged();
            }
        }
        private global::System.String _COMMENTS;
        partial void OnCOMMENTSChanging(global::System.String value);
        partial void OnCOMMENTSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RATING
        {
            get
            {
                return _RATING;
            }
            set
            {
                OnRATINGChanging(value);
                ReportPropertyChanging("RATING");
                _RATING = StructuralObject.SetValidValue(value, "RATING");
                ReportPropertyChanged("RATING");
                OnRATINGChanged();
            }
        }
        private Nullable<global::System.Int32> _RATING;
        partial void OnRATINGChanging(Nullable<global::System.Int32> value);
        partial void OnRATINGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> RADIO
        {
            get
            {
                return _RADIO;
            }
            set
            {
                OnRADIOChanging(value);
                ReportPropertyChanging("RADIO");
                _RADIO = StructuralObject.SetValidValue(value, "RADIO");
                ReportPropertyChanged("RADIO");
                OnRADIOChanged();
            }
        }
        private Nullable<global::System.Boolean> _RADIO;
        partial void OnRADIOChanging(Nullable<global::System.Boolean> value);
        partial void OnRADIOChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MusicModel", Name="SONG")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SONG : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SONG object.
        /// </summary>
        /// <param name="tITLE">Initial value of the TITLE property.</param>
        /// <param name="rATING">Initial value of the RATING property.</param>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="uPLOADED">Initial value of the UPLOADED property.</param>
        public static SONG CreateSONG(global::System.String tITLE, global::System.Int32 rATING, global::System.Int32 id, global::System.Boolean uPLOADED)
        {
            SONG sONG = new SONG();
            sONG.TITLE = tITLE;
            sONG.RATING = rATING;
            sONG.ID = id;
            sONG.UPLOADED = uPLOADED;
            return sONG;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TITLE
        {
            get
            {
                return _TITLE;
            }
            set
            {
                OnTITLEChanging(value);
                ReportPropertyChanging("TITLE");
                _TITLE = StructuralObject.SetValidValue(value, false, "TITLE");
                ReportPropertyChanged("TITLE");
                OnTITLEChanged();
            }
        }
        private global::System.String _TITLE;
        partial void OnTITLEChanging(global::System.String value);
        partial void OnTITLEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ARTIST
        {
            get
            {
                return _ARTIST;
            }
            set
            {
                OnARTISTChanging(value);
                ReportPropertyChanging("ARTIST");
                _ARTIST = StructuralObject.SetValidValue(value, true, "ARTIST");
                ReportPropertyChanged("ARTIST");
                OnARTISTChanged();
            }
        }
        private global::System.String _ARTIST;
        partial void OnARTISTChanging(global::System.String value);
        partial void OnARTISTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ALBUM
        {
            get
            {
                return _ALBUM;
            }
            set
            {
                OnALBUMChanging(value);
                ReportPropertyChanging("ALBUM");
                _ALBUM = StructuralObject.SetValidValue(value, true, "ALBUM");
                ReportPropertyChanged("ALBUM");
                OnALBUMChanged();
            }
        }
        private global::System.String _ALBUM;
        partial void OnALBUMChanging(global::System.String value);
        partial void OnALBUMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GENRE
        {
            get
            {
                return _GENRE;
            }
            set
            {
                OnGENREChanging(value);
                ReportPropertyChanging("GENRE");
                _GENRE = StructuralObject.SetValidValue(value, true, "GENRE");
                ReportPropertyChanged("GENRE");
                OnGENREChanged();
            }
        }
        private global::System.String _GENRE;
        partial void OnGENREChanging(global::System.String value);
        partial void OnGENREChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> DURATION
        {
            get
            {
                return _DURATION;
            }
            set
            {
                OnDURATIONChanging(value);
                ReportPropertyChanging("DURATION");
                _DURATION = StructuralObject.SetValidValue(value, "DURATION");
                ReportPropertyChanged("DURATION");
                OnDURATIONChanged();
            }
        }
        private Nullable<global::System.Int64> _DURATION;
        partial void OnDURATIONChanging(Nullable<global::System.Int64> value);
        partial void OnDURATIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> BITRATE
        {
            get
            {
                return _BITRATE;
            }
            set
            {
                OnBITRATEChanging(value);
                ReportPropertyChanging("BITRATE");
                _BITRATE = StructuralObject.SetValidValue(value, "BITRATE");
                ReportPropertyChanged("BITRATE");
                OnBITRATEChanged();
            }
        }
        private Nullable<global::System.Int64> _BITRATE;
        partial void OnBITRATEChanging(Nullable<global::System.Int64> value);
        partial void OnBITRATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> FILESIZE
        {
            get
            {
                return _FILESIZE;
            }
            set
            {
                OnFILESIZEChanging(value);
                ReportPropertyChanging("FILESIZE");
                _FILESIZE = StructuralObject.SetValidValue(value, "FILESIZE");
                ReportPropertyChanged("FILESIZE");
                OnFILESIZEChanged();
            }
        }
        private Nullable<global::System.Int64> _FILESIZE;
        partial void OnFILESIZEChanging(Nullable<global::System.Int64> value);
        partial void OnFILESIZEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RATING
        {
            get
            {
                return _RATING;
            }
            set
            {
                OnRATINGChanging(value);
                ReportPropertyChanging("RATING");
                _RATING = StructuralObject.SetValidValue(value, "RATING");
                ReportPropertyChanged("RATING");
                OnRATINGChanged();
            }
        }
        private global::System.Int32 _RATING;
        partial void OnRATINGChanging(global::System.Int32 value);
        partial void OnRATINGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COMMENTS
        {
            get
            {
                return _COMMENTS;
            }
            set
            {
                OnCOMMENTSChanging(value);
                ReportPropertyChanging("COMMENTS");
                _COMMENTS = StructuralObject.SetValidValue(value, true, "COMMENTS");
                ReportPropertyChanged("COMMENTS");
                OnCOMMENTSChanged();
            }
        }
        private global::System.String _COMMENTS;
        partial void OnCOMMENTSChanging(global::System.String value);
        partial void OnCOMMENTSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ARTIST_ID
        {
            get
            {
                return _ARTIST_ID;
            }
            set
            {
                OnARTIST_IDChanging(value);
                ReportPropertyChanging("ARTIST_ID");
                _ARTIST_ID = StructuralObject.SetValidValue(value, "ARTIST_ID");
                ReportPropertyChanged("ARTIST_ID");
                OnARTIST_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _ARTIST_ID;
        partial void OnARTIST_IDChanging(Nullable<global::System.Int32> value);
        partial void OnARTIST_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LOCATION
        {
            get
            {
                return _LOCATION;
            }
            set
            {
                OnLOCATIONChanging(value);
                ReportPropertyChanging("LOCATION");
                _LOCATION = StructuralObject.SetValidValue(value, true, "LOCATION");
                ReportPropertyChanged("LOCATION");
                OnLOCATIONChanged();
            }
        }
        private global::System.String _LOCATION;
        partial void OnLOCATIONChanging(global::System.String value);
        partial void OnLOCATIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean UPLOADED
        {
            get
            {
                return _UPLOADED;
            }
            set
            {
                OnUPLOADEDChanging(value);
                ReportPropertyChanging("UPLOADED");
                _UPLOADED = StructuralObject.SetValidValue(value, "UPLOADED");
                ReportPropertyChanged("UPLOADED");
                OnUPLOADEDChanged();
            }
        }
        private global::System.Boolean _UPLOADED;
        partial void OnUPLOADEDChanging(global::System.Boolean value);
        partial void OnUPLOADEDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] HASH
        {
            get
            {
                return StructuralObject.GetValidValue(_HASH);
            }
            set
            {
                OnHASHChanging(value);
                ReportPropertyChanging("HASH");
                _HASH = StructuralObject.SetValidValue(value, true, "HASH");
                ReportPropertyChanged("HASH");
                OnHASHChanged();
            }
        }
        private global::System.Byte[] _HASH;
        partial void OnHASHChanging(global::System.Byte[] value);
        partial void OnHASHChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MusicModel", "FK_SONG_RATED_SONG", "SONG_RATED")]
        public EntityCollection<SONG_RATED> SONG_RATED
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SONG_RATED>("MusicModel.FK_SONG_RATED_SONG", "SONG_RATED");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SONG_RATED>("MusicModel.FK_SONG_RATED_SONG", "SONG_RATED", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MusicModel", Name="SONG_RATED")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SONG_RATED : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SONG_RATED object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="sONG_ID">Initial value of the SONG_ID property.</param>
        public static SONG_RATED CreateSONG_RATED(global::System.Int32 id, global::System.Int32 sONG_ID)
        {
            SONG_RATED sONG_RATED = new SONG_RATED();
            sONG_RATED.ID = id;
            sONG_RATED.SONG_ID = sONG_ID;
            return sONG_RATED;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SONG_ID
        {
            get
            {
                return _SONG_ID;
            }
            set
            {
                OnSONG_IDChanging(value);
                ReportPropertyChanging("SONG_ID");
                _SONG_ID = StructuralObject.SetValidValue(value, "SONG_ID");
                ReportPropertyChanged("SONG_ID");
                OnSONG_IDChanged();
            }
        }
        private global::System.Int32 _SONG_ID;
        partial void OnSONG_IDChanging(global::System.Int32 value);
        partial void OnSONG_IDChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MusicModel", "FK_SONG_RATED_SONG", "SONG")]
        public SONG SONG
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SONG>("MusicModel.FK_SONG_RATED_SONG", "SONG").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SONG>("MusicModel.FK_SONG_RATED_SONG", "SONG").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SONG> SONGReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SONG>("MusicModel.FK_SONG_RATED_SONG", "SONG");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SONG>("MusicModel.FK_SONG_RATED_SONG", "SONG", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
