//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject1.AzureMusic {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceWebRole1")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SONG", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceWebRole1", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class SONG : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALBUMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ARTISTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ARTIST_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> BITRATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMMENTSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> DURATIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> FILESIZEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GENREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] HASHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOCATIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RATINGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestProject1.AzureMusic.SONG_RATED[] SONG_RATEDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TITLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UPLOADEDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALBUM {
            get {
                return this.ALBUMField;
            }
            set {
                this.ALBUMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ARTIST {
            get {
                return this.ARTISTField;
            }
            set {
                this.ARTISTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ARTIST_ID {
            get {
                return this.ARTIST_IDField;
            }
            set {
                this.ARTIST_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> BITRATE {
            get {
                return this.BITRATEField;
            }
            set {
                this.BITRATEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COMMENTS {
            get {
                return this.COMMENTSField;
            }
            set {
                this.COMMENTSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> DURATION {
            get {
                return this.DURATIONField;
            }
            set {
                this.DURATIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> FILESIZE {
            get {
                return this.FILESIZEField;
            }
            set {
                this.FILESIZEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GENRE {
            get {
                return this.GENREField;
            }
            set {
                this.GENREField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] HASH {
            get {
                return this.HASHField;
            }
            set {
                this.HASHField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOCATION {
            get {
                return this.LOCATIONField;
            }
            set {
                this.LOCATIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RATING {
            get {
                return this.RATINGField;
            }
            set {
                this.RATINGField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestProject1.AzureMusic.SONG_RATED[] SONG_RATED {
            get {
                return this.SONG_RATEDField;
            }
            set {
                this.SONG_RATEDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TITLE {
            get {
                return this.TITLEField;
            }
            set {
                this.TITLEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UPLOADED {
            get {
                return this.UPLOADEDField;
            }
            set {
                this.UPLOADEDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SONG_RATED", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceWebRole1", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class SONG_RATED : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestProject1.AzureMusic.SONG SONGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.Objects.DataClasses.EntityReference<TestProject1.AzureMusic.SONG> SONGReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SONG_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestProject1.AzureMusic.SONG SONG {
            get {
                return this.SONGField;
            }
            set {
                this.SONGField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReference<TestProject1.AzureMusic.SONG> SONGReference {
            get {
                return this.SONGReferenceField;
            }
            set {
                this.SONGReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SONG_ID {
            get {
                return this.SONG_IDField;
            }
            set {
                this.SONG_IDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AzureMusic.IServiceMusic")]
    public interface IServiceMusic {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMusic/GetData", ReplyAction="http://tempuri.org/IServiceMusic/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMusic/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceMusic/GetDataUsingDataContractResponse")]
        TestProject1.AzureMusic.CompositeType GetDataUsingDataContract(TestProject1.AzureMusic.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMusic/GetMellowSongs", ReplyAction="http://tempuri.org/IServiceMusic/GetMellowSongsResponse")]
        TestProject1.AzureMusic.SONG[] GetMellowSongs(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMusic/GetRandomSongs", ReplyAction="http://tempuri.org/IServiceMusic/GetRandomSongsResponse")]
        TestProject1.AzureMusic.SONG[] GetRandomSongs(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMusic/GetRecentSongs", ReplyAction="http://tempuri.org/IServiceMusic/GetRecentSongsResponse")]
        TestProject1.AzureMusic.SONG[] GetRecentSongs(int num);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceMusicChannel : TestProject1.AzureMusic.IServiceMusic, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceMusicClient : System.ServiceModel.ClientBase<TestProject1.AzureMusic.IServiceMusic>, TestProject1.AzureMusic.IServiceMusic {
        
        public ServiceMusicClient() {
        }
        
        public ServiceMusicClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceMusicClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceMusicClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceMusicClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public TestProject1.AzureMusic.CompositeType GetDataUsingDataContract(TestProject1.AzureMusic.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public TestProject1.AzureMusic.SONG[] GetMellowSongs(int num) {
            return base.Channel.GetMellowSongs(num);
        }
        
        public TestProject1.AzureMusic.SONG[] GetRandomSongs(int num) {
            return base.Channel.GetRandomSongs(num);
        }
        
        public TestProject1.AzureMusic.SONG[] GetRecentSongs(int num) {
            return base.Channel.GetRecentSongs(num);
        }
    }
}
